version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: dendgau
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mynetwork

 #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 10880:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - mynetwork
  #Mysl Service
  db:
    image: mysql:8
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: Aa1231
      MYSQL_PASSWORD: Aa1231
    ports:
      - 13306:3306
    volumes:
      - ./.db:/var/lib/mysql
      - ./.docker/mysql/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - mynetwork

#Networks
networks:
  mynetwork:
    driver: bridge
